/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Otp Start */
        post: operations["otp_start_v1_auth_otp_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Otp Verify */
        post: operations["otp_verify_v1_auth_otp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Profile */
        get: operations["my_profile_v1_profiles_me_get"];
        /** Update My Profile */
        put: operations["update_my_profile_v1_profiles_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profiles/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile By Id */
        get: operations["get_profile_by_id_v1_profiles__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/verified-attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Verified Attributes */
        get: operations["my_verified_attributes_v1_users_me_verified_attributes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entitlements/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog
         * @description Public feature catalog: which plans unlock each feature.
         */
        get: operations["catalog_v1_entitlements_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entitlements/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Entitlements */
        get: operations["my_entitlements_v1_entitlements_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Subscription */
        post: operations["create_subscription_v1_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Subscription */
        get: operations["get_my_subscription_v1_subscriptions_me_get"];
        /** Update My Subscription */
        put: operations["update_my_subscription_v1_subscriptions_me_put"];
        post?: never;
        /** Cancel My Subscription */
        delete: operations["cancel_my_subscription_v1_subscriptions_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/verification-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Verification
         * @description Placeholder — returns 501 by design until compliance sign-off.
         *
         *     Wired now so the route exists and the block is explicit and testable,
         *     rather than a missing endpoint someone silently implements later.
         */
        post: operations["start_verification_v1_verification_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discovery */
        get: operations["discovery_v1_discovery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_v1_matches_get"];
        put?: never;
        /** Create Match */
        post: operations["create_match_v1_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match */
        get: operations["get_match_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_v1_matches__match_id__conversation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_v1_matches__match_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/date-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Date Prompt */
        get: operations["get_date_prompt_v1_matches__match_id__date_prompt_get"];
        put?: never;
        /**
         * Trigger Date Prompt
         * @description Advance match to DATE_PROMPT_PENDING.
         *
         *     System-triggered in production (scheduled after 3-5 days of chat).
         *     Exposed here so the flow is exercisable without scheduler infrastructure.
         */
        post: operations["trigger_date_prompt_v1_matches__match_id__date_prompt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/date-prompt/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Date Prompt Response */
        post: operations["submit_date_prompt_response_v1_matches__match_id__date_prompt_response_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Availability */
        post: operations["submit_availability_v1_matches__match_id__availability_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/venue-recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Venue Recommendations */
        get: operations["get_venue_recommendations_v1_matches__match_id__venue_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/date-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Date Plan */
        post: operations["create_date_plan_v1_matches__match_id__date_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/date-plan/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Date Outcome */
        post: operations["record_date_outcome_v1_matches__match_id__date_plan_outcome_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/coaching-insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coaching Insights */
        get: operations["coaching_insights_v1_matches__match_id__coaching_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/compatibility-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compatibility Score */
        get: operations["compatibility_score_v1_matches__match_id__compatibility_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountState
         * @description User onboarding state machine (docs/architecture/overview.md).
         *
         *     Auth (OTP) gets a user to REGISTERED; the Vetted domain moves them toward
         *     VERIFIED_AND_ELIGIBLE. See ADR-0001 on why auth != identity verification.
         * @enum {string}
         */
        AccountState: "REGISTERED" | "PROFILE_INCOMPLETE" | "VERIFICATION_PENDING" | "VERIFICATION_IN_REVIEW" | "VERIFIED_AND_ELIGIBLE" | "PROFILE_ACTIVE";
        /** AvailabilityOut */
        AvailabilityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Slots */
            slots: unknown[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AvailabilitySubmit */
        AvailabilitySubmit: {
            /** Slots */
            slots: string[];
        };
        /**
         * BillingCycle
         * @enum {string}
         */
        BillingCycle: "monthly" | "annual";
        /** CoachingInsightsOut */
        CoachingInsightsOut: {
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Insight Tier */
            insight_tier: string;
            /** Insights */
            insights: components["schemas"]["InsightItem"][];
        };
        /** CompatibilityScoreOut */
        CompatibilityScoreOut: {
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Score */
            score: number;
            /** Factors */
            factors: {
                [key: string]: unknown;
            } | null;
            /** Signals Summary */
            signals_summary: {
                [key: string]: unknown;
            } | null;
        };
        /** ConversationOut */
        ConversationOut: {
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            state: components["schemas"]["MatchState"];
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
        };
        /**
         * CriminalCheckStatus
         * @enum {string}
         */
        CriminalCheckStatus: "pending" | "passed" | "failed" | "disputed";
        /**
         * DateOutcome
         * @enum {string}
         */
        DateOutcome: "went_well" | "did_not_go_well" | "no_show" | "cancelled";
        /** DateOutcomeSubmit */
        DateOutcomeSubmit: {
            outcome: components["schemas"]["DateOutcome"];
        };
        /** DatePlanCreate */
        DatePlanCreate: {
            /** Venue Name */
            venue_name: string;
            /** Venue Address */
            venue_address?: string | null;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
        };
        /** DatePlanOut */
        DatePlanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Venue Name */
            venue_name: string;
            /** Venue Address */
            venue_address: string | null;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            outcome: components["schemas"]["DateOutcome"] | null;
            /** Outcome Recorded At */
            outcome_recorded_at: string | null;
        };
        /**
         * DatePromptChoice
         * @enum {string}
         */
        DatePromptChoice: "yes" | "no" | "maybe";
        /** DatePromptResponseCreate */
        DatePromptResponseCreate: {
            choice: components["schemas"]["DatePromptChoice"];
        };
        /**
         * DatePromptStateOut
         * @description Prompt state visible to the requesting user.
         *
         *     counterpart_choice is withheld until both parties have responded to
         *     preserve the simultaneous-reveal guarantee.
         */
        DatePromptStateOut: {
            /** Active */
            active: boolean;
            my_choice: components["schemas"]["DatePromptChoice"] | null;
            /** Resolved */
            resolved: boolean;
            counterpart_choice?: components["schemas"]["DatePromptChoice"] | null;
            resolved_state?: components["schemas"]["MatchState"] | null;
        };
        /** DiscoveryProfileOut */
        DiscoveryProfileOut: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Display Name */
            display_name: string | null;
            /** Bio */
            bio: string | null;
            /** Photos */
            photos: unknown[] | null;
            /** Interests */
            interests: unknown[] | null;
            /** City Market */
            city_market: string | null;
        };
        /**
         * Eligibility
         * @enum {string}
         */
        Eligibility: "eligible" | "ineligible" | "exception_granted";
        /** EntitlementsOut */
        EntitlementsOut: {
            /** Effective Plan */
            effective_plan: string;
            /** Subscription Status */
            subscription_status: string | null;
            /** Features */
            features: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IncomePercentileTier
         * @enum {string}
         */
        IncomePercentileTier: "0-25" | "25-50" | "50-75" | "75-90" | "90+";
        /** InsightItem */
        InsightItem: {
            /** Type */
            type: string;
            /** Tier */
            tier: string;
            /** Body */
            body: string;
        };
        /** MatchCreate */
        MatchCreate: {
            /**
             * Target User Id
             * Format: uuid
             */
            target_user_id: string;
        };
        /** MatchOut */
        MatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User A Id
             * Format: uuid
             */
            user_a_id: string;
            /**
             * User B Id
             * Format: uuid
             */
            user_b_id: string;
            state: components["schemas"]["MatchState"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MatchState
         * @enum {string}
         */
        MatchState: "CHAT_OPEN" | "DATE_PROMPT_PENDING" | "DATE_PROMPT_CAPTURED" | "EXTENDED_CHAT" | "SCHEDULE_READY" | "CLOSED";
        /** MessageCreate */
        MessageCreate: {
            /** Body */
            body: string;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /**
             * Sender Id
             * Format: uuid
             */
            sender_id: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OtpStartRequest */
        OtpStartRequest: {
            /** Destination */
            destination: string;
            /** Channel */
            channel: string;
        };
        /** OtpStartResponse */
        OtpStartResponse: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Dev Code */
            dev_code?: string | null;
        };
        /** OtpVerifyRequest */
        OtpVerifyRequest: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Code */
            code: string;
        };
        /**
         * Plan
         * @enum {string}
         */
        Plan: "premium" | "premium_plus" | "elite";
        /** ProfileOut */
        ProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Display Name */
            display_name: string | null;
            /** Bio */
            bio: string | null;
            /** Prompts */
            prompts: unknown[] | null;
            /** Photos */
            photos: unknown[] | null;
            /** Interests */
            interests: unknown[] | null;
            /** Dining Preferences */
            dining_preferences: {
                [key: string]: unknown;
            } | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** City Market */
            city_market: string | null;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Bio */
            bio?: string | null;
            /** Prompts */
            prompts?: unknown[] | null;
            /** Photos */
            photos?: unknown[] | null;
            /** Interests */
            interests?: unknown[] | null;
            /** Dining Preferences */
            dining_preferences?: {
                [key: string]: unknown;
            } | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** City Market */
            city_market?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
        };
        /** SubscriptionCreate */
        SubscriptionCreate: {
            plan: components["schemas"]["Plan"];
            billing_cycle: components["schemas"]["BillingCycle"];
        };
        /** SubscriptionOut */
        SubscriptionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            plan: components["schemas"]["Plan"];
            billing_cycle: components["schemas"]["BillingCycle"];
            status: components["schemas"]["SubscriptionStatus"];
            /** Activation Fee Paid At */
            activation_fee_paid_at: string | null;
            /** Current Period Start */
            current_period_start: string | null;
            /** Current Period End */
            current_period_end: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SubscriptionStatus
         * @enum {string}
         */
        SubscriptionStatus: "active" | "past_due" | "canceled" | "expired";
        /** SubscriptionUpdate */
        SubscriptionUpdate: {
            plan?: components["schemas"]["Plan"] | null;
            billing_cycle?: components["schemas"]["BillingCycle"] | null;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string | null;
            status: components["schemas"]["UserStatus"];
            account_state: components["schemas"]["AccountState"];
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "active" | "suspended" | "deleted" | "banned";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VenueRecommendationOut */
        VenueRecommendationOut: {
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Cuisine */
            cuisine: string;
            /** Price Tier */
            price_tier: string;
        };
        /** VerifiedAttributesOut */
        VerifiedAttributesOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Identity Verified */
            identity_verified: boolean;
            criminal_check_status: components["schemas"]["CriminalCheckStatus"];
            income_percentile_tier: components["schemas"]["IncomePercentileTier"] | null;
            /** Education Level */
            education_level: string | null;
            eligibility: components["schemas"]["Eligibility"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    otp_start_v1_auth_otp_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    otp_verify_v1_auth_otp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    my_profile_v1_profiles_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    update_my_profile_v1_profiles_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_by_id_v1_profiles__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_verified_attributes_v1_users_me_verified_attributes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifiedAttributesOut"];
                };
            };
        };
    };
    catalog_v1_entitlements_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    my_entitlements_v1_entitlements_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementsOut"];
                };
            };
        };
    };
    create_subscription_v1_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_subscription_v1_subscriptions_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
        };
    };
    update_my_subscription_v1_subscriptions_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_my_subscription_v1_subscriptions_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_verification_v1_verification_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    discovery_v1_discovery_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryProfileOut"][];
                };
            };
        };
    };
    list_matches_v1_matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"][];
                };
            };
        };
    };
    create_match_v1_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_v1_matches__match_id__conversation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_v1_matches__match_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_date_prompt_v1_matches__match_id__date_prompt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatePromptStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_date_prompt_v1_matches__match_id__date_prompt_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_date_prompt_response_v1_matches__match_id__date_prompt_response_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatePromptResponseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatePromptStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_availability_v1_matches__match_id__availability_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilitySubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_venue_recommendations_v1_matches__match_id__venue_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueRecommendationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_date_plan_v1_matches__match_id__date_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatePlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatePlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_date_outcome_v1_matches__match_id__date_plan_outcome_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DateOutcomeSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatePlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coaching_insights_v1_matches__match_id__coaching_insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachingInsightsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compatibility_score_v1_matches__match_id__compatibility_score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityScoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
