"""catch up matchmaking/structured/intelligent tables + admin module

0001_initial only ever covered identity/entitlements/verification; the
matchmaking, structured, and intelligent modules built after it were never
given their own migration (dev ran on SQLite auto-create, which doesn't need
one). This migration brings a Postgres DB at 0001_initial fully current,
alongside the new admin module (moderation_cases, audit_events, beta_invites,
users.is_admin).

Revision ID: ec68fcccadaa
Revises: 0001_initial
Create Date: 2026-08-05 23:02:05.575872
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.common.base


revision: str = 'ec68fcccadaa'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_type', sa.Enum('SYSTEM', 'ADMIN', 'USER', name='audit_actor_type'), nullable=False),
    sa.Column('actor_id', app.common.base.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=False),
    sa.Column('subject_id', app.common.base.GUID(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.common.base.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beta_invites',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('invited_by', app.common.base.GUID(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.common.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('matches',
    sa.Column('user_a_id', app.common.base.GUID(), nullable=False),
    sa.Column('user_b_id', app.common.base.GUID(), nullable=False),
    sa.Column('state', sa.Enum('CHAT_OPEN', 'DATE_PROMPT_PENDING', 'DATE_PROMPT_CAPTURED', 'EXTENDED_CHAT', 'SCHEDULE_READY', 'CLOSED', name='match_state'), nullable=False),
    sa.Column('id', app.common.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id')
    )
    op.create_table('moderation_cases',
    sa.Column('reporter_id', app.common.base.GUID(), nullable=False),
    sa.Column('subject_type', sa.Enum('USER', 'MESSAGE', 'PROFILE', name='moderation_subject_type'), nullable=False),
    sa.Column('subject_id', app.common.base.GUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACTIONED', 'DISMISSED', name='moderation_status'), nullable=False),
    sa.Column('assigned_admin_id', app.common.base.GUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.common.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_windows',
    sa.Column('match_id', app.common.base.GUID(), nullable=False),
    sa.Column('user_id', app.common.base.GUID(), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.Column('id', app.common.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'user_id')
    )
    op.create_table('conversation_signals',
    sa.Column('match_id', app.common.base.GUID(), nullable=False),
    sa.Column('user_a_id', app.common.base.GUID(), nullable=False),
    sa.Column('user_b_id', app.common.base.GUID(), nullable=False),
    sa.Column('message_count_a', sa.Integer(), nullable=False),
    sa.Column('message_count_b', sa.Integer(), nullable=False),
    sa.Column('avg_message_length_a', sa.Float(), nullable=True),
    sa.Column('avg_message_length_b', sa.Float(), nullable=True),
    sa.Column('avg_reply_latency_a_seconds', sa.Float(), nullable=True),
    sa.Column('avg_reply_latency_b_seconds', sa.Float(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('score_factors', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.common.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('date_plans',
    sa.Column('match_id', app.common.base.GUID(), nullable=False),
    sa.Column('venue_name', sa.Text(), nullable=False),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.Enum('WENT_WELL', 'DID_NOT_GO_WELL', 'NO_SHOW', 'CANCELLED', name='date_outcome'), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.common.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('date_prompt_responses',
    sa.Column('match_id', app.common.base.GUID(), nullable=False),
    sa.Column('user_id', app.common.base.GUID(), nullable=False),
    sa.Column('choice', sa.Enum('YES', 'NO', 'MAYBE', name='date_prompt_choice'), nullable=False),
    sa.Column('id', app.common.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('match_id', app.common.base.GUID(), nullable=False),
    sa.Column('sender_id', app.common.base.GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', app.common.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_table('messages')
    op.drop_table('date_prompt_responses')
    op.drop_table('date_plans')
    op.drop_table('conversation_signals')
    op.drop_table('availability_windows')
    op.drop_table('moderation_cases')
    op.drop_table('matches')
    op.drop_table('beta_invites')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
